# Generated by Django 5.0.3 on 2024-04-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviedata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='Dname',
            field=models.CharField(default='Nolan', max_length=200),
        ),
    ]
